"""rentals table and relation to books

Revision ID: 44a63a0746f6
Revises: 4ebe0daa0fc7
Create Date: 2022-07-19 14:05:17.374277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a63a0746f6'
down_revision = '4ebe0daa0fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_rental_date'), 'rental', ['rental_date'], unique=False)
    op.create_index(op.f('ix_rental_return_date'), 'rental', ['return_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_return_date'), table_name='rental')
    op.drop_index(op.f('ix_rental_rental_date'), table_name='rental')
    op.drop_table('rental')
    # ### end Alembic commands ###
